{
 "title": "Logs",
 "tags": [ "logs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"app\", level = \"error\"}"
    }
   ]
  },
  {
   "title": "Log Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (compose_service) (rate({compose_service=\"app\"}[5m]))"
    }
   ]
  },
  {
   "title": "Logs - Go CRUD",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{compose_service=\"app\"} |= \"\""
    }
   ]
  },
  {
   "title": "Database Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{compose_service=\"db\"} |= \"\""
    }
   ]
  }
 ]
}